### PR TITLE
3.3.1: Fixed crash and improved pip-service detection

### PR DESCRIPTION
**Pull request by svenh0**
- Fixed crash caused by referenced local variable 
- improved pip-service detection on show ibts

### CODE REVIEW

**Comment by mtdcr** [comment]
Thanks!

**Comment by mtdcr** [comment]
The rebase & merge didn't do what I intended, so I just force-pushed master to 1fea517efcc5fefa0c391689dfaa71437d349989 in order to avoid a merge commit. We might as well switch back to the upstream repository and delete this fork.

**Comment by svenh0** [comment]
Thanks also
I don't know what is the best way for this.
I thought, this fork is the base for the deb-file in the dreamos-update.
from which source cames the Code for building the deb-file?
http://www.dreamboxupdate.com/opendreambox/2.5/unstable/r0/dm920/deb/cortexa15hf-neon-vfpv4/enigma2-plugin-extensions-infobartunerstate_3.3.0+git1+d3b1a24ade-r0.0_armhf.deb

**Comment by mtdcr** [comment]
Apparently we already switched to git://github.com/betonme/e2openplugin-InfoBarTunerState.git one year ago. It's time to delete this repository to avoid more confusion.

**Pull request merged**
